"""
Django settings for spotter_backend project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# in production this MUST come from the environment; the fallback is a
# throwaway value that only exists so `manage.py runserver` works out of
# the box for local dev.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-p^c=dw$&dt1bn254(^@##ww99u=!y5i8psj0x)58-qkq0n2%@a',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,.onrender.com"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'tripplanner',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://spotter-trip-planner.vercel.app",
    "https://spotter-trip-planner-git-main-morpheusout.vercel.app",
]
# deploy-time origins (Render sets this via env; dev keeps the list above)
CORS_ALLOWED_ORIGINS += [
    o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()
]
# fail closed: an org tool with protected endpoints should never ship allow-all.
# add the real deploy origin to CORS_ALLOWED_ORIGINS instead of flipping this.
CORS_ALLOW_ALL_ORIGINS = os.environ.get("DJANGO_CORS_ALLOW_ALL", "").lower() == "true" and DEBUG
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'spotter_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spotter_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Production uses Postgres via DATABASE_URL (Render add-on); local dev
# falls back to sqlite so `manage.py runserver` works with zero setup.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

import dj_database_url  # noqa: E402
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# single-company app: one fleet, one set of roles
AUTH_USER_MODEL = 'tripplanner.User'

# DRF
# authenticated by default — public endpoints opt out with AllowAny.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # the planner + suggest both call free third-party services
        # (OSRM, Nominatim); rate limit them per-user so one page of
        # tabs can't burn the fleet's quota.
        'plan': '20/hour',
        'suggest': '60/min',
        # compliance packet exports are cheap (reportlab) but can pile
        # up fast on a fleet board; keep them bounded per user.
        'export': '30/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# auth token lifetimes — access token rides in the SPA's memory, refresh
# in localStorage. short access window limits what a lifted token exposes.
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# watchdog debounce: how many minutes must pass before a new alert for the
# same (driver, rule) can fire again, even after the previous one was
# cleared. the free-tier Render cron runs hourly (default handles that
# fine); a self-hosted deployment can schedule it every few minutes and
# bump this down without spamming the alert queue.
WATCH_HOS_FIRE_MINUTES = int(os.environ.get('WATCH_HOS_FIRE_MINUTES', '20'))

# OpenAPI schema (drf-spectacular) — served at /api/schema/ + /api/docs/.
# auth-marker so generated clients know every endpoint except login/explore
# expects a JWT bearer token.
SPECTACULAR_SETTINGS = {
    'TITLE': 'Spotter HOS Trip Planner API',
    'DESCRIPTION': (
        'Single-company trip planning + HOS guardrail tool. '
        'Authenticate with a JWT Bearer token; roles gate the surface '
        '(driver sees own trips, dispatcher/admin manage the fleet, '
        'auditor reads only).'
    ),
    'VERSION': '0.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'Bearer': []}],
}

# structured logging: local dev keeps humane console lines, production
# (env VAR SPOTTER_JSON_LOGS=true) emits JSON lines for the platform logger.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {'format': '[%(asctime)s] %(levelname)s %(name)s %(message)s'},
        'json': {
            'format': '{"ts":"%(asctime)s","level":"%(levelname)s",'
                      '"logger":"%(name)s","msg":"%(message)s"}'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json' if os.environ.get('SPOTTER_JSON_LOGS', '').lower() == 'true'
                         else 'console',
        },
    },
    'root': {'handlers': ['console'], 'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')},
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# render.yaml runs `collectstatic --noinput`; without a STATIC_ROOT that build step dies
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
