# Generated by Django 5.2.17 on 2026-09-10 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tripplanner.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
