# Generated by Django 5.2.17 on 2026-09-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0002_tripevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='rule',
            field=models.CharField(choices=[('drive_11', 'Daily drive 11h'), ('duty_14', 'Daily duty 14h'), ('cycle_70', 'Cycle 70h'), ('over_hours', 'Over hours')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('stopped', 'Stopped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripevent',
            name='at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('dispatcher', 'Dispatcher'), ('admin', 'Admin'), ('auditor', 'Auditor')], default='driver', help_text='Role gates API surface: drivers see only their own trips.', max_length=20),
        ),
    ]
