# Generated by Django 5.2.17 on 2026-09-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0003_alter_alert_rule_alter_alert_triggered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty Not Driving')], db_index=True, max_length=24)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_events', to='tripplanner.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_events', to='tripplanner.trip')),
            ],
            options={
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['driver', 'started_at'], name='duty_driver_start_idx')],
            },
        ),
    ]
